name: "CI"
on:
  pull_request:
  push:
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2.3.4
    - name: Checkout arduino-ci
      uses: actions/checkout@v2.3.4
      with:
         repository: pololu/arduino-ci
         path: ci
    - name: Cache for arduino-ci
      uses: actions/cache@v2.1.3
      with:
        path: |
          ~/.arduino15
        key: ${{ runner.os }}-arduino
    - name: Install nix
      uses: cachix/install-nix-action@v12
    - run: ci/ci
      env:
        ARDUINO_CI_ONLY_BOARDS: arduino:avr:leonardo,arduino:avr:uno
